WebAppSofie/WebAppSofie/urls.py
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import javascript_catalog
# from viaSofie.admin import admin_site

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
admin.site.site_header = 'Via Sofie Administratie'

import settings

js_info_dict = {
    'packages': ('viaSofie',),
}

urlpatterns =[

    url(r'^admin', include(admin.site.urls)),
    # url(r'^myadmin', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('viaSofie.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^$', include('viaSofie.urls')),
    # user auth urls
]

urlpatterns += i18n_patterns([url(r'^$', 'viaSofie.views.index', name='home')])


if not settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()

WebAppSofie/viaSofie/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
#from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^$', views.index),
    # url(r'^account', views.account),
    url(r'^accounts/status', views.account),
    url(r'^accounts/login',  views.login),
    url(r'^accounts/auth',  views.auth_view),
    url(r'^accounts/logout', views.logout),
    url(r'^accounts/loggedin', views.loggedin),
    url(r'^accounts/invalid', views.invalid_login),
    url(r'^accounts/register', views.register_user),
    url(r'^accounts/register_success', views.register_success),
    url(r'^sales/forSale', views.offer_sales),
    url(r'^sales/forRent', views.offer_rent),
    url(r'^sales/property/(?P<p_id>[0-9]+)/$', views.property),
    url(r'^about/viaSofie$', views.about),
    url(r'^ebook', views.ebook),
    url(r'^contact', views.contact),
    # url(r'^search/', include('haystack.urls')),
    url(r'^search/', views.pandensearch),
    url(r'^partner', views.partner),
    url(r'^faq', views.faq),
    url(r'^info/privacy', views.privacy),
    url(r'^info/disclaimer', views.disclaimer),
    url(r'^newsletter/subscribe', views.newsletterSubscribe),
    url(r'^newsletter/unsubscribe', views.newsletterUnsubscribe),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebAppSofie/viaSofie/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from tinymce.models import HTMLField
from datetime import datetime
import time
import googlemaps
import json
import datetime
import ssl
from django.db.models.signals import post_save
from django.db.models.signals import pre_save
from django.db.models.signals import post_delete
from django.dispatch import receiver
from tinymce import models as tinymce_models
from datetime import date
from django.http import HttpResponseRedirect
from django.core.files.storage import FileSystemStorage
import sys
import traceback

# ssl._create_default_https_context = ssl._create_unverified_context
fs = FileSystemStorage()

class UserDetails(models.Model):
	user = models.OneToOneField(User)
	phonenumber = models.CharField('Telefoonnummer', max_length=12)
	street = models.CharField('Straat', max_length=50)
	housenumber = models.CharField('Huisnummer', max_length=4)
	busnumber = models.CharField('Busnummer', max_length=3, null=True, blank=True)
	postalcode = models.CharField('Postcode', max_length=10)
	city = models.CharField('Plaats', max_length=30)
	country = models.CharField('Land', max_length=30)

class Aboutpage(models.Model):
	title = models.CharField('titel', max_length=60)
	text = tinymce_models.HTMLField()
	language = models.CharField('taal', max_length=20, default='NL')
	class Meta:
		verbose_name_plural = "Over ons pagina"

class PrivacyPage(models.Model):
	title = models.CharField('titel', max_length=60)
	text = HTMLField()
	language = models.CharField('taal', max_length=20)
	class Meta:
		verbose_name_plural = "Privacy pagina"

class DisclaimerPage(models.Model):
	title = models.CharField('titel', max_length=60)
	text = HTMLField()
	language = models.CharField('taal', max_length=20)
	class Meta:
		verbose_name_plural = "Disclaimer pagina"

class Ebook(models.Model):
	name = models.CharField('naam', max_length=20)
	path = models.FilePathField(max_length=100, editable=False)
	language = models.CharField('taal', max_length=3)
	available = models.BooleanField('Beschikbaar', default=True)
	class Meta:
		verbose_name_plural = "Ebooks"

	def __unicode__(self):
		return u'{0}'.format(self.name)

class EbookRequests(models.Model):
	email = models.EmailField(max_length=70)
	ebook_id = models.ForeignKey(Ebook, blank=True, null=True, on_delete=models.PROTECT)
	send = models.BooleanField()
	class Meta:
		verbose_name_plural = "EbookRequests"
		verbose_name = "EbookRequest"

class Properties(models.Model):
	user = models.ForeignKey(User, on_delete=models.PROTECT)
	title_dutch = models.CharField(max_length=100)
	title_french = models.CharField(max_length=100)
	street = models.CharField('straat', max_length=50)
	housenumber = models.CharField('huisnummer', max_length=4)
	busnumber = models.CharField('busnummer', max_length=3, blank=True)
	postalcode = models.CharField('postcode', max_length=10)
	city = models.CharField('dorp/stad', max_length=30)
	longitude = models.CharField(max_length=10, editable=False)
	latitude = models.CharField(max_length=10, editable=False)
	price = models.CharField('prijs', max_length=8)
	BUILDINGTYPE = (
		('O', 'Open'),
		('H', 'Half'),
		('CL', 'Closed'),
		('A', 'Appartment'),
		('M', 'Mezzanine'),
		('B', 'Bungalow'),
		('CA', 'Caravan'),
	)
	buildingtype = models.CharField('gebouwtype', max_length=2, choices=BUILDINGTYPE, default=BUILDINGTYPE[0][0])
	sale = models.BooleanField('verkopen', default=True)
	area = models.CharField('oppervlakte', max_length=10)
	livingarea = models.CharField('leef oppervlakte', max_length=10)
	year = models.CharField('bouwjaar', max_length=4) #buildyear
	rateable_value = models.CharField('kadastraal inkomen', max_length=8) #kadastraal inkomen
	description_dutch = models.TextField()
	description_french = models.TextField()
	HEATING_TYPE = (
		('E', 'Electric'),
		('G', 'Gas'),
		('F', 'Furnace'),
		('H', 'Heat pump'),
		('S', 'Special'),
	)
	heating_type = models.CharField('verwarmingstype', max_length=1, choices=HEATING_TYPE, default=HEATING_TYPE[0][0])
	energy_label = models.CharField('energie label', max_length=5)
	extra_information_dutch = models.TextField()
	extra_information_french = models.TextField()
	available = models.BooleanField('Beschikbaar', default=True)
	sold = models.BooleanField('verkocht')
	date_created = models.DateTimeField(editable=False)
	date_modified = models.DateTimeField(editable=False)
	pub_date = models.DateTimeField()
	class Meta:
		verbose_name_plural = "Panden"
		verbose_name = "Pand"

	def get_priorityImage(self):
		priorityImage = Photo.objects.filter(property_id = self, priority = True)
		return priorityImage

	def save(self, *args, **kwargs):
		# Property_street=self.street
		# Property_streetnumber=self.housenumber
		# Property_postalcode=self.postalcode
		# Property_city=self.city
		#
		# # making the url for the google maps.
		# location=Property_street+Property_streetnumber+','+Property_postalcode+Property_city
		#
		# gmaps = googlemaps.Client(key='AIzaSyDP2GIaLZod3VOwu9rh0fdyxbiNBAmNswE')
		#
	    # # Geocoding an address
		# geocode_result = gmaps.geocode(location)
		#
		# if (geocode_result):
	    # # query json
		# 	latitude = geocode_result[0]["geometry"]["location"]["lat"]
		# 	longitude = geocode_result[0]["geometry"]["location"]["lng"]
		#
		#     # adding longitude and latitude to the database
		# 	self.longitude = longitude
		# 	self.latitude = latitude
		# else:
		# 	raise ValidationError({'street': 'controleer straatnaam'})
		# 	raise ValidationError({'housenumber': 'controleer huisnummer'})
		# 	raise ValidationError({'postalcode': 'controleer postcode'})
		# 	raise ValidationError({'city': 'controleer gemeente'})
		# full link to google maps geolocation api with right key: https://maps.googleapis.com/maps/api/geocode/json?address=Lindelei35,2620Hemiksem&key=AIzaSyCpFy6NnC1cbEvM8bLRAgzGskxYUeTL-_M

		if not self.id:
			self.date_created = datetime.datetime.now()
		self.date_modified = datetime.datetime.now()
		return super(Properties, self).save(*args, **kwargs)
	def __unicode__(self):
		return  self.title_dutch

class PropertyDocuments(models.Model):
	property_id = models.ForeignKey(Properties, on_delete=models.CASCADE)
	name = models.CharField(max_length=30, default = 'Pand Informatie')
	document = models.FileField(storage = fs, upload_to = 'uploads/', null=True)
	available = models.BooleanField('Bestand weergeven')
	remove_the_file = models.BooleanField('Verwijder document')

	def save(self):
		if self.remove_the_file:
			super(PropertyDocuments, self).delete()
			return
		super(PropertyDocuments, self).save()


class Partner(models.Model):
	name = models.CharField(max_length=30)
	text = models.TextField()
	photo = models.ImageField(storage = fs, default='/media/partner.jpg')
	available = models.BooleanField('zichtbaar')
	class Meta:
		verbose_name_plural = "Partners"
		verbose_name = "Partner"

class PlanningInfo(models.Model): #moet nog vertaald worden
	property_id = models.ForeignKey(Properties, on_delete=models.CASCADE)
	voorkooprecht = models.BooleanField()
	bouwvergunning = models.BooleanField()
	dagvaarding = models.BooleanField()
	verkaveling = models.BooleanField()
	juridische_beslissing = models.BooleanField()
	co2_emission = models.CharField(max_length=5)
	epc = models.CharField(max_length=10)
	unique_code = models.CharField(max_length=10)

class Photo(models.Model):
	property_id = models.ForeignKey(Properties, on_delete=models.CASCADE)
	photo = models.ImageField(storage = fs)
	priority = models.BooleanField('Kies als hoofdfoto')
	remove_the_file = models.BooleanField('Verwijder foto')
	def image_thumb(self):
		return '<img src="/media/%s" width="100" height="100" />' % (self.photo)
	image_thumb.allow_tags = True

	def save(self):
		if self.remove_the_file:
			super(Photo, self).delete()
			return
		super(Photo, self).save()

class Room(models.Model):
	property_id = models.ForeignKey(Properties, on_delete=models.CASCADE)
	area = models.CharField('oppervlakte', max_length=8)

	class meta:
		abstract = True

class Bathroom(Room):
	bath_type = models.CharField('type bad', max_length=15)
	class Meta:
		verbose_name = "Badkamer"

class Bedroom(Room):
	class Meta:
		verbose_name = "Slaapkamer"

class Garage(Room):
	pass

class Toilet(Room):
	class Meta:
		verbose_name_plural = "Toiletten"

class Kitchen(Room):
	class Meta:
		verbose_name = "Keuken"

class Livingroom(Room):
	class Meta:
		verbose_name = "Woonkamer"

class Storageroom(Room):
	class Meta:
		verbose_name_plural = "Bergingen"
		verbose_name = "Berging"

class Basement(Room):
	class Meta:
		verbose_name = "Kelder"

class Attic(Room):
	class Meta:
		verbose_name = "Zolder"

class Translations(models.Model):
	english = models.CharField(max_length=30)
	french = models.CharField(max_length=30)
	dutch = models.CharField(max_length=30)

class Faq(models.Model):
	question = models.TextField('vraag')
	answer = tinymce_models.HTMLField('antwoord')
	visible = models.BooleanField('zichtbaar', default=True)
	pub_date = models.DateTimeField()

	def __unicode__(self):
		return self.question

	class Meta:
		verbose_name_plural = "Faq's"
		verbose_name = "Faq"

class Newsletter(models.Model):
	email = models.EmailField()
	class Meta:
		verbose_name_plural = "Nieuwsbrief"
		verbose_name = "Nieuwsbrief"

class Status(models.Model):
	STATUS = [
		('', ''),
		('WB', 'Word Behandeld'),
		('C', 'Compromis'),
		('F', 'Finale Akte'),
	]
	datum = models.DateField(default=date.today)
	dossierStatus = models.CharField(max_length=2, choices=STATUS, default=STATUS[0][0])
	eigendom = models.ForeignKey(Properties,on_delete=models.CASCADE)
	class Meta:
		verbose_name_plural = "Status"

@receiver(post_delete, sender=Photo)
def photo_post_delete_handler(sender, **kwargs):
	picture = kwargs['instance']
	storage, path = picture.photo.storage, picture.photo.path
	storage.delete(path)

@receiver(post_delete, sender=PropertyDocuments)

WebAppSofie/templates/account.html
{% extends "templates/base.html" %}

{% block content %}
  <h1>{{ info.first_name }} {{ info.last_name }}<h1>
  <h3>Mijn Panden</h3>
  <div class = ".container-fluid">
    <div class = "row inline-block-row">
    {% for property in properties %}
      <div class ="col-md-3">
        <div class="card">
          <!-- <h4>{{ property.title_dutch }}</h4> -->
          {% if property.get_priorityImage %}
          {% for image in property.get_priorityImage %}
          <img class="card-img-top test12 img-rounded img-fluid" src="{{ image.photo.url }}" alt="Card image cap">
          {%endfor%}
          {%else%}
          <img class="card-img-top test12 img-rounded img-fluid" src="/media/nophoto.png" alt="Card image cap">
          {%endif%}
          <div class="card-block text-xs-center">
				    <h4 class="card-title test123">{{ property.title_dutch }}</h4>
				    <!-- <p class="card-text test12">{{ property.description_dutch }}</p> -->
            {% for e in status %}
              {% if e.eigendom_id = property.id %}
                <p class="card-text test12"><b>Status:</b>{{ e.get_dossierStatus_display }}</p>
              {% endif %}
            {% endfor%}
				    <a href="/sales/property/{{ property.id }}/" class="btn btn-house">Read More</a>
				  </div>
        </div>
      </div>
      {% if forloop.counter|divisibleby:"4" %}
        <div class="clearfix visible-md-block"></div>
      {% endif %}
    {%endfor%}
    </div>
  </div>
{% endblock %}

WebAppSofie/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Via Sofie{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href = "{% static "WebAppSofie/css/bootstrap-v4.min.css" %}" rel ="stylesheet">
    <link href = "{% static "WebAppSofie/css/styles.css" %}" rel ="stylesheet">
    <script src="{% static "WebAppSofie/css/jquery-2.0.0.min.js"%}"></script>
    <script src="{% static "WebAppSofie/js/bootstrap-v4.min.js"%}"></script>

</head>

<body>
  <div class="container">
      <nav id="header" class ="navbar navbar-dark bg-inverse navbar-fixed-top">
        <div class="col-md-3">
          <a class="navbar-brand" href="/"><img src="{% static "WebAppSofie/img/def_logos_via_sofie-RGB-01.png" %}" style="max-height: 100px; max-width: 100px;" class="img-rounded"></a>
        </div>
        <div class="col-md-9">
       <button id="navbar-toggler" class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header">&#9776;</button>
       <div class="collapse navbar-toggleable-sm" id="navbar-header">
         {% block menubar %}
         <ul class="nav navbar-nav nav-pills pull-xs-right">
           {% if user.is_authenticated %}
           <li class="nav-item"><a class="nav-link" href="/accounts/status">Mijn panden</a></li>
           <li class="nav-item"><a class="nav-link" href="/accounts/logout">Logout</a></li>
           {% else %}
           <li class="nav-item"><a class="nav-link" href="/accounts/login">Login</a></li>
           {% endif %}
           <li class="nav-item"><a class="nav-link" href="/sales/forSale">Kopen</a></li>
           <li class="nav-item"><a class="nav-link" href="/sales/forRent">Huren</a></li>
           <li class="nav-item"><a class="nav-link" href="/about/viaSofie">Over</a></li>
           <li class="nav-item"><a class="nav-link" href="/faq">Advies</a></li>
           <li class="nav-item"><a class="nav-link" href="/contact">Contact</a></li>
           <li class="nav-item"><a class="nav-link" href="/partner">Partners</a></li>
           <li class="nav-item"><a class="nav-link" href="/newsletter/subscribe">Nieuwsbrief</a></li>
           <li class="nav-item"><a class="nav-link" href="/ebook">E_book</a></li>
         </ul>

         <form id="searchform" class="form-inline pull-xs-right" type="get" action="http://193.191.187.253:8093/search/.">
            <input class="form-control" type="text" placeholder="Search" name="q">
            <button class="btn btn-success-outline" type="submit">Search</button>
          </form>
         {% endblock %}
      </div>
    </div>
     </nav>
    <div class="content">
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>
    <footer class="footer">
      <div class="row">
        <div class="col-md-3">
          <span class="navbar-text pull-lg-left">BIV 509141</span>
          <span class="navbar-text pull-lg-right">&copy; Via Sofie 2016</span>
        </div>
        <div class="col-md-6 col-md-offset-3">
          <span class="pull-lg-right">
            <a href="/faq">Vastgoed &amp; advies</a> |
            <a href="/info/disclaimer">Disclaimer</a> |
            <a href="">Sitemap</a> |
            <a href="/info/privacy">Privacybeleid</a>
          </span>
        </div>
      </div>
    </footer>
  </div>
</body>
</html>

WebAppSofie/templates/disclaimer.html
{% extends "templates/base.html" %}

{% block content %}

		{% for disclaimer in Disclaimer %}
		<h2>{{ disclaimer.title }}</h2>
		<h4>{{ disclaimer.text | safe}}</h4>
		</bk>
		{% endfor %}

{% endblock %}

WebAppSofie/templates/ebook.html
{% extends "templates/base.html" %}

{% block content %}


	<div class = "container"><!--hier start midden content-->
	<h2>Ebook aanvragen:</h2>
	<form action="/ebook" method="post" role="form" class="form-horizontal">{% csrf_token %}
		<!-- {{form}} -->
		{% for field in form %}
			<div class="form-group">
				<div class='row'>
	        		<label class="control-label col-md-2" for="{{ field.name }}">{{ field.label }}</label>
					<div class="col-md-7">
						{{ field }} {{ field.errors }}
					</div>
				</div>
			</div>
    	{% endfor %}
		<div class="form-group">
    	<div class="col-sm-offset-1 col-sm-7">
      	<input type="submit" value="Register" class="btn btn-default"/>
    	</div>
  	</div>
	</form>
</div><!--hier eindigt midden content-->

{% endblock %}

WebAppSofie/templates/home.html
{% extends "templates/base.html" %}
{% load static %}
{% block content %}

<div class = "container"><!--hier begint de boven content-->
	<div class = "jumbotron jumbotron-static-top" >
		<center>
			<img src="{% static "WebAppSofie/images/def_logos_via_sofie-RGB-01.png" %}" width="20%" height="5%"  class="img-rounded"/>
			<p>Welkom op via Sofie. Deze website is bedoeld om u extra informatie te verschaffen over beschikbare panden.</p>
			<p>Hebt u nog interesse kan u mij altijd contacteren of naar 1 van mijn partners gaan.</p>
			<a class = "btn btn-default" href="/contact">Contacteer mij</a>
			<a class = "btn btn-default" href="/partner">Partners</a>
		</center>
	</div>
</div><!--hier eindigt de boven content-->

<div class = "container"><!--hier start midden content-->
	<h3>Te koop</h3>
	<div class="row">
		<center>
			{% for sale in Sales %}
			<div class ="col-md-3">
				<div class="card">
					{% if sale.get_priorityImage %}
					{% for image in sale.get_priorityImage %}
					<img class="card-img-top test12 img-rounded img-fluid" src="{{ image.photo.url }}" alt="Card image cap">
					{%endfor%}
					{%else%}
					<img class="card-img-top test12 img-rounded img-fluid" src="/media/nophoto.png" alt="Card image cap">
					{%endif%}
					<div class="card-block text-xs-center">
						<h4 class="card-title test123">{{ sale.title_dutch }}</h4>
						<p class="card-text test12">{{ sale.description_dutch }}</p>
						<a href="/sales/property/{{ sale.id }}/" class="btn btn-house">Read More</a>
					</div>
				</div>
			</div>
			{% if forloop.counter|divisibleby:"4" %}
				<div class="clearfix visible-md-block"></div>
			{% endif %}
			{%endfor%}
		</center>
	</div>
	<h3>Te Huur</h3>
	<div class="row">
		<center>
			{% for rent in Rents %}
			<div class ="col-md-3">
				<div class="card">
					{% if rent.get_priorityImage %}
					{% for image in rent.get_priorityImage %}
					<img class="card-img-top test12 img-rounded img-fluid" src="{{ image.photo.url }}" alt="Card image cap">
					{%endfor%}
					{%else%}
					<img class="card-img-top test12 img-rounded img-fluid" src="/media/nophoto.png" alt="Card image cap">
					{%endif%}
					<div class="card-block text-xs-center">
						<h4 class="card-title test123">{{ rent.title_dutch }}</h4>
						<p class="card-text test12">{{ rent.description_dutch }}</p>
						<a href="/sales/property/{{ rent.id }}/" class="btn btn-house">Read More</a>
					</div>
				</div>
			</div>
			{% if forloop.counter|divisibleby:"4" %}
				<div class="clearfix visible-md-block"></div>
			{% endif %}
			{%endfor%}
		</center>
	</div>
	<h2>Maatschappelijk engagement</h2>
	<div class="row">
		<center>
			<div class="col-md-offset-4 col-md-5">
				<p>Als onderneming wil Via Sofie iets terugdoen voor de maatschappij. Van elke verkoop gaat een deel van de commissie naar een goed doel.
					Deze twee projecten worden ondersteund:</p>
			</div>
			<div class="col-md-offset-1 col-md-5 card">
				<p>Moeders voor moeders zet zich in voor de armsten in Vlaanderen :<br>
				<a class="nav-link" href="http://www.moedersvoormoeders.be">www.moedersvoormoeders.be</a></p>
			</div>
			<div class="col-md-offset-1 col-md-5 card">
				<p>Ondernemers zonder Grenzen, een organisatie die  zich, met een uniek herbebossingsproject inzet voor het welzijn van mens én planeet:<br>
				<a class="nav-link" href="http://www.ozg.be">www.ozg.be</a></p>
			</div>
		</center>
	</div>
	<div class="row">
		<center>
			<div class="col-md-offset-4 col-md-5">
				<p>Laat gerust weten welk project  u mee een duwtje in de rug wilt geven!</p>
			</div>
		</center>
	</div>
</div>
<div class="clearfix"></div>

{% endblock %}

WebAppSofie/templates/index.html
<p>hello</p>

WebAppSofie/templates/invalid_login.html
{% extends "templates/base.html" %}

{% block content %}

	<h2>Your login details are invalid!</h2>
	<p>Click <a href="/accounts/login">here</a> to try again.</p>

{% endblock %}

WebAppSofie/templates/loggedin.html
{% extends "templates/base.html" %}

{% block content %}
<div class="container">
	<h2>Hi {{full_name}} you're now logged in!</h2>
	<p>Click <a href="/accounts/logout/">here</a> to logout.</p>
	<p>Click <a href="/accounts/status/">here</a> to go to your account page.</p>
</div>

{% endblock %}

WebAppSofie/templates/login.html
{% extends "templates/base.html" %}

{% block content %}

	{% if form.errors %}
		<p class="error"> Sorry, that's not a valid username or password</p>
	{% endif %}
	<div class="container">
	<form action="/accounts/auth/" class="form-horizontal" method="post" role="form">{% csrf_token %} <!-- cross site scripting defend token -->
		<div class="form-group">
			<div class="row">
				<label class="control-label col-sm-2" for="username">Username:</label>
				<div class="col-sm-6">
					<input type="text" name="username" value="" class="form-control" id="username">
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<label class="control-label col-sm-2" for="password">Password:</label>
				<div class="col-sm-6">
					<input type="password" name="password" class="form-control" value="" id="password">
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
	    	<div class="col-sm-offset-2 col-sm-6">
					<input type="submit" class="form-control" value="login" />
				</div>
			</div>
		</div>
	</form>
</div>
{% endblock %}

WebAppSofie/templates/logout.html
{% extends "templates/base.html" %}

{% block content %}

  <h2>Logged out!</h2>
  <p>Click <a href="/accounts/login/">here</a> to login again</p>
  

{% endblock %}

WebAppSofie/templates/newsletter.html
{% extends "templates/base.html" %}

{% block content %}


	<h2>Inschrijven nieuwsbrief</h2>
	<form role="form" action="" method="post">
		{% csrf_token %}
		{{ form }}<br>
		<button type="submit">Inschrijven</button>
	</form>
	<a href="/newsletter/unsubscribe">Klik hier om uit te schrijven</a>

{% endblock %}

WebAppSofie/templates/notes.html
{% extends "templates/base.html" %}

{% block content %}
  <h2>Aanbod</h2>
  <div class = ".container-fluid">
  	<div class = "row inline-block-row">
  		{% for pand in panden %}
        <div class ="col-md-3">
  				<div class="card">
            <!-- {% if pand.photo %} -->
    					<!-- {% for image in pand.photo %} -->
                <!-- {% if image.available = 1 %} -->
      					<img class="card-img-top test12 img-rounded img-fluid" src="{{ pand.photo.url }}" alt="Card image cap">
                <!-- {%endif%} -->
    					<!-- {%endfor%} -->
  					<!-- {%else%} -->
  					<!-- <img class="card-img-top test12 img-rounded img-fluid" src="/media/nophoto.png" alt="Card image cap"> -->
  					<!-- {%endif%} -->
  				  <div class="card-block text-xs-center">
  				    <h4 class="card-title test123">{{ pand.title_dutch }}</h4>
  				    <p class="card-text test12">{{ pand.description_dutch }}</p>
  				    <a id="test1" href="/sales/property/{{ pand.pand_id }}/" class="btn btn-house">Read More</a>
  				  </div>
  				</div>
        </div>
  			{% if forloop.counter|divisibleby:"4" %}
  				<div class="clearfix visible-md-block"></div>
  			{% endif %}
  		{%endfor%}
  	</div>
  </div>
{% endblock %}

WebAppSofie/templates/partner.html
{% extends "templates/base.html" %}

{% block content %}
<div class = ".container-fluid">
	<div class = "row inline-block-row">
		{% for partner in Partner %}
		<div class ="col-md-2 col-sm-2">
			<div class ="test123">
				<h3>{{ partner.name }}</h3>
			</div>
			<div class ="test12">
				<img src="{{partner.photo.url}}" width="90%"height="10%"  class="img-rounded img-responsive"/>
			</div>
			<p>{{ partner.text }}
		</div>
		</bk>
		{% endfor %}
	</div>
</div>

{% endblock %}

WebAppSofie/templates/status.html
{% extends "templates/base.html" %}

{% block content %}
	<h1>{{ info.first_name }} {{ info.last_name }}<h1>
	<h4>Dossier Status</h4>
  <p>{{ status }}</p>
{% endblock %}